name: Python CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tools: ["ruff", "bandit", "pytest"]
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/login@v1.5.1
        continue-on-error: true
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ${{ matrix.tools }}
        uses: microsoft/action-python@0.7.2
        with:
          ${{ matrix.tools }}: true
          args: ${{ matrix.args }}
          workdir: src
          testdir: tests
          python_version: 3.10.13

  # publish:
  #   uses: microsoft/action-python/.github/workflows/publish.yml@0.6.4
  #   secrets:
  #     PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  #     TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
